[build-system]
requires = ["setuptools>=65", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gwsignal4gwsurr"
dynamic = ["version"]
description = "gwsignal implementation to use waveform models from gwsurrogate"
dependencies = ["numpy", "scipy", "bilby", "astropy"]

[tool.setuptools.packages.find]
where = ["."]
include = ["gwsignal4gwsurr"]
